---
- name: Create pandda configuration directory
  ansible.builtin.file:
    path: /etc/pandda.d/
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Upload main pandda configuration file
  ansible.builtin.copy:
    src: "{{ inventory_dir }}/host_files/{{ inventory_hostname }}/pandda.yaml"
    dest: "{{ pandda_conf_path }}pandda.yaml"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: true
    force: true

- name: Create directory /opt/pandda/
  ansible.builtin.file:
    path: /opt/pandda/
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- name: Upload configuration generator script
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "/opt/pandda/{{ item }}"
    owner: root
    group: root
    mode: "0755"
    backup: true
    force: true
  loop:
    - adict_basic_auth_conf.py
    - adict_conf.py
    - ipfixcol2_conf.py
    - ipfixprobe_conf.py
    - instance_ipfixprobe.conf.j2


- name: Install Python packages for config generators
  ansible.builtin.pip:
    name:
      - bcrypt~=4.0
      - pyyaml~=6.0
      - jinja2
