---
- name: Enable NEMEA module groups
  ansible.builtin.command: supen -d {{ item }} -g {{ item }}
  changed_when: true
  with_items:
    - adict_prefix_filter
    - adict_ip_activity
    - adict_open_ports
    - adict_recog
  tags: configure

- name: Apply changes in supervisor configuration
  ansible.builtin.command: "{{ item }}"
  changed_when: true
  loop:
    - "supervisorctl reread"
    - "supervisorctl update"
    - "supervisorctl start adict_prefix_filter:"
    - "supervisorctl start adict_ip_activity:"
    - "supervisorctl start adict_open_ports:"
    - "supervisorctl start adict_recog:"
  tags: configure
