---
- name: Install NEMEA ADiCT package
  ansible.builtin.dnf:
    name: nemea-adict
    state: latest # noqa package-latest
  tags: install

- name: Copy configuration files
  ansible.builtin.copy:
    src: files/configs/
    dest: /etc/supervisord.d/configs/
    owner: root
    group: root
    mode: '0644'
  tags: configure

- name: Ensure /etc/nemea_adict directory exists
  ansible.builtin.file:
    name: /etc/nemea_adict
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: configure

- name: Copy generator configuration to /etc/pandda.d/
  ansible.builtin.template:
    src: files/nemea_adict_filters.yml
    dest: "{{ pandda_conf_path }}/nemea_adict_filters.yml"
    owner: "root"
    group: "root"
    mode: "0644"
  tags: configure

- name: Execute adict configuration generator
  ansible.builtin.command:
    cmd: "{{ pandda_conf_executable }} {{ pandda_conf_opt }}/adict_conf.py {{ pandda_conf_path }}/nemea_adict_filters.yml"
  args:
    creates:
      - /etc/nemea_adict/prefix_filter_single
      - /etc/nemea_adict/prefix_filter_bi
      - /etc/nemea_adict/prefixes.conf
  tags: configure

- name: Ensure /etc/nemea_adict/recog directory exists
  ansible.builtin.file:
    name: /etc/nemea_adict/recog
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: configure

- name: Copy Recog module configuration
  ansible.builtin.copy:
    src: files/recog/
    dest: /etc/nemea_adict/recog/
    owner: root
    group: root
    mode: '0644'
  tags: configure

- name: Enable NEMEA module groups
  ansible.builtin.command: supen -d {{ item }} -g {{ item }}
  changed_when: true
  with_items:
    - adict_prefix_filter
    - adict_ip_activity
    - adict_open_ports
    - adict_recog
  tags: configure

- name: Apply changes in supervisor configuration
  ansible.builtin.command: "{{ item }}"
  changed_when: true
  loop:
    - "supervisorctl reread"
    - "supervisorctl update"
    - "supervisorctl start adict_prefix_filter:"
    - "supervisorctl start adict_ip_activity:"
    - "supervisorctl start adict_open_ports:"
    - "supervisorctl start adict_recog:"
  tags: configure
