---
- name: Set install_adict if not defined to default value
  ansible.builtin.set_fact:
    install_adict: "{{ install_adict | default(false) | bool }}"

- name: Set remove_adict if not defined to default value
  ansible.builtin.set_fact:
    remove_adict: "{{ remove_adict | default(false) | bool }}"

- name: Set disable_adict if not defined to default value
  ansible.builtin.set_fact:
    disable_adict: "{{ disable_adict | default(false) | bool }}"

- name: Set enable_adict if not defined to default value
  ansible.builtin.set_fact:
    enable_adict: "{{ enable_adict | default(install_adict) | bool }}"

- name: Set etcdir if not defined to default value
  ansible.builtin.set_fact:
    etcdir: "{{ etcdir | default('adict') }}"

- name: Set installdir if not defined to default value
  ansible.builtin.set_fact:
    installdir: "{{ installdir | default('/adict') }}"

- name: Set venvdir if not defined to default value
  ansible.builtin.set_fact:
    venvdir: "{{ venvdir | default('/dp3-venv') }}"

- name: Set app_name if not defined to default value
  ansible.builtin.set_fact:
    app_name: "{{ app_name | default('adict') }}"

- name: Set workers if not defined to default value
  ansible.builtin.set_fact:
    workers: "{{ workers | default(2) }}"

- name: Set memory_limit if not defined
  ansible.builtin.set_fact:
    memory_limit: "{{ memory_limit | default('1g') }}"

- name: Set mongo_data_path if not defined
  ansible.builtin.set_fact:
    mongo_data_path: "{{ mongo_data_path | default('/data/db') }}"

- name: Print ADICT variables
  ansible.builtin.debug:
    msg:
      - "remove_adict: {{ remove_adict }}"
      - "install_adict: {{ install_adict }}"
      - "disable_adict: {{ disable_adict }}"
      - "enable_adict: {{ enable_adict }}"
      - "etcdir: {{ etcdir }}"
      - "installdir: {{ installdir }}"
      - "venvdir: {{ venvdir }}"
      - "app_name: {{ app_name }}"
      - "workers: {{ workers }}"
      - "memory_limit: {{ memory_limit }}"
      - "mongo_data_path: {{ mongo_data_path }}"
