- name: Import RPM keys for RabbitMQ server
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - "https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc"
    - "https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.E495BB49CC4BBE5B.key"
    - "https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.9F4587F226208342.key"

- name: Copy rabbitmq.repo file
  ansible.builtin.copy:
    src: rabbitmq-{{ epel_version }}.repo
    dest: /etc/yum.repos.d/rabbitmq.repo
    owner: root
    group: root
    mode: "0644"

- name: Update dnf
  ansible.builtin.dnf:
    update_cache: true

- name: Install RabbitMQ and dependencies
  ansible.builtin.dnf:
    name: ["erlang", "rabbitmq-server", "socat", "logrotate"]
    state: present

- name: Copy rabbitmq-env.conf file
  ansible.builtin.copy:
    src: rabbitmq-env.conf
    dest: /etc/rabbitmq/rabbitmq-env.conf
    owner: root
    group: root
    mode: "0644"

- name: Stop and disable service
  ansible.builtin.include_tasks: disable.yml
  tags: configure
  when: disable_adict

- name: Start and enable service
  ansible.builtin.include_tasks: enable.yml
  tags: configure
  when: enable_adict
