- name: Override /opt/adict/config/snapshots.yml
  ansible.builtin.copy:
    src: "snapshots.yml"
    dest: /opt/adict/config/snapshots.yml
    mode: "0644"
  tags:
    - install
    - configure

- name: Restart ADiCT service
  ansible.builtin.command: "systemctl restart adict"
  tags:
    - install
    - configure

- name: Restart ADiCT supervisor modules
  ansible.builtin.command: "adictctl restart all"
  tags:
    - install
    - configure
