- name: Override /opt/adict/config/snapshots.yml
  ansible.builtin.copy:
    src: "snapshots.yml"
    dest: /opt/adict/config/snapshots.yml
    mode: "0644"
  tags:
    - install
    - configure

- name: Override /opt/adict/config/db_entities/ip.yml
  ansible.builtin.copy:
    src: "ip.yml"
    dest: /opt/adict/config/db_entities/ip.yml
    mode: "0644"
  tags:
    - install
    - configure

- name: Restart ADiCT service
  ansible.builtin.command: "systemctl restart adict"
  tags:
    - install
    - configure

- name: Restart ADiCT supervisor modules
  ansible.builtin.command: "adictctl restart all"
  tags:
    - install
    - configure

- name: Patch /usr/lib64/ipfixprobe/config2args.py
  ansible.builtin.copy:
    src: "config2args.py"
    dest: /usr/lib64/ipfixprobe/config2args.py
    mode: "0755"
  tags:
    - install
    - configure

- name: Restart ipfixprobe
  ansible.builtin.command: "systemctl restart 'ipfixprobe@*'"
  tags:
    - install
    - configure

- name: Remove pandda_gui package
  ansible.builtin.command: "dnf remove -y pandda_gui"
  tags:
    - install
    - configure

- name: Copy patched pandda_gui package
  ansible.builtin.copy:
    src: "pandda_gui-0.5.1-Linux.rpm"
    dest: /tmp
  tags:
    - install
    - configure

- name: Install patched pandda_gui package
  ansible.builtin.command: "rpm -i /tmp/pandda_gui-0.5.1-Linux.rpm"
  tags:
    - install
    - configure
