- name: Install dependencies for dp3
  ansible.builtin.dnf:
    name: ["redis", "socat", "logrotate"]
    state: present

- name: Create Python virtual environment for DP3
  ansible.builtin.command:
    cmd: python3.9 -m venv {{ venvdir }}
    creates: "{{ venvdir }}/bin/activate"

- name: Install dp3 from git
  ansible.builtin.pip:
    name: "dp-cubed[deploy]~=0.9.0"
    state: present
    virtualenv: "{{ venvdir }}"
