- name: Install python3 and pip
  ansible.builtin.dnf:
    name: ["python3", "python3-pip", "redis", "socat", "logrotate"]
    state: present # noqa package-latest

- name: Start and enable redis service
  ansible.builtin.service:
    name: redis
    state: started
    enabled: true

- name: Upgrade pip
  ansible.builtin.pip:
    name: pip
    version: "21.1.3"  # Specify the desired version here

- name: Create Python virtual environment for DP3
  ansible.builtin.command:
    cmd: python3 -m venv {{ venvdir }}
    creates: "{{ venvdir }}/bin/activate"

- name: Install dp3 from git
  ansible.builtin.pip:
    name: "git+https://github.com/CESNET/dp3.git#egg=dp-cubed[deploy]"
    state: present
    virtualenv: "{{ venvdir }}"
