---
- name: Stop MongoDB container
  ansible.builtin.systemd:
    name: mongodb-{{ app_name }}
    state: stopped
    enabled: false
  failed_when: false
  tags: uninstall

- name: Remove systemd service file
  ansible.builtin.file:
    path: /etc/systemd/system/mongodb-{{ app_name }}.service
    state: absent
  tags: uninstall

- name: Remove docker-compose file
  ansible.builtin.file:
    path: /data/docker-compose.yml
    state: absent
  tags: uninstall

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  tags: uninstall
