- name: Install python3 and pip for EPEL 8
  ansible.builtin.dnf:
    name: ["python39", "python39-pip", "python3-requests"]
    state: present
  when: epel_version is defined and epel_version=="8"

- name: Install python3 and pip for EPEL 9
  ansible.builtin.dnf:
    name: ["python3.9", "python3.9-pip", "python-requests"]
    state: present
  when: epel_version is defined and epel_version=="9"
