- name: Install python3 and pip
  ansible.builtin.dnf:
    name: ["python3", "python3-pip"]
    state: present # noqa package-latest

- name: Upgrade pip
  ansible.builtin.pip:
    name: pip
    version: "21.1.3"  # Specify the desired version here

- name: Install basic python packages
  ansible.builtin.dnf:
    name: ["python3-requests"]
    state: present # noqa package-latest
