- name: Install python3 and pip for EPEL 8
  ansible.builtin.dnf:
    name: ["python39", "python39-pip", "python3-requests"]
    state: present # noqa package-latest
  when: epel_version is defined and epel_version=="8"

- name: Install python3 and pip for EPEL 9
  ansible.builtin.dnf:
    name: ["python3.9", "python3.9-pip", "python-requests"]
    state: present # noqa package-latest
  when: epel_version is defined and epel_version=="9"

- name: Upgrade pip
  ansible.builtin.pip:
    name: pip
    version: "21.1.3"
