- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest # noqa package-latest
    update_cache: true
  tags: install

- name: Ensure configuration directories exists
  ansible.builtin.file:
    path: /etc/{{ item }}
    state: directory
    owner: root
    group: root
    mode: "0755"
  with_items:
    - nginx/
    - nginx/default.d/
  tags: configure

- name: Copy configuration
  ansible.builtin.template:
    src: files/{{ item }}
    dest: /etc/nginx/{{ item }}
    owner: root
    group: root
    mode: "0644"
  with_items:
    - nginx.conf
    - default.d/api.conf
    - default.d/frontend.conf
  tags: configure

- name: Execute basic HTTP auth configuration generator
  ansible.builtin.command:
    cmd: "{{ pandda_conf_executable }} {{ pandda_conf_opt }}/adict_basic_auth_conf.py -f {{ pandda_conf_path }}adict.htpasswd"
  changed_when: true
  tags: configure

- name: Generate SSL certificates
  ansible.builtin.import_tasks: generate_certs.yml
  tags: configure

- name: Disable firewall and nginx
  ansible.builtin.include_tasks: disable.yml
  tags: configure
  when: disable_adict

- name: Enable firewall and nginx
  ansible.builtin.include_tasks: enable.yml
  tags: configure
  when: enable_adict
