- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present # noqa package-latest
    update_cache: true
  tags: install

- name: Copy configuration
  ansible.builtin.template:
    src: files/{{ item }}
    dest: /etc/nginx/{{ item }}
    owner: root
    group: root
    mode: "0644"
  with_items:
    - nginx.conf
    - default.d/api.conf
    - default.d/frontend.conf
  tags: configure
  register: nginx_conf

- name: Generate SSL certificates
  ansible.builtin.import_tasks: generate_certs.yml

- name: Restart and enable nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
  tags: install

- name: Ensure firewalld is not masked, enabled and running
  ansible.builtin.systemd:
    name: firewalld
    masked: false
    enabled: true
    state: started
  tags: install

- name: Open port 80/tcp
  ansible.posix.firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
  tags: install

- name: Open port 443/tcp
  ansible.posix.firewalld:
    port: 443/tcp
    permanent: true
    state: enabled
  tags: install

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  changed_when: true
  tags: install
