- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest # noqa package-latest
    update_cache: true
  tags: install

- name: Copy configuration
  ansible.builtin.template:
    src: files/{{ item }}
    dest: /etc/nginx/{{ item }}
    owner: root
    group: root
    mode: "0644"
  with_items:
    - nginx.conf
    - default.d/api.conf
    - default.d/frontend.conf
  tags: configure

- name: Execute basic HTTP auth configuration generator
  ansible.builtin.command:
    cmd: >
      {{ pandda_conf_executable }} {{ pandda_conf_opt }}/adict_basic_auth_conf.py
      --config '[{username: {{ adict_gui_user }}, password: {{ adict_gui_pass }}}]'
      --file {{ pandda_conf_path }}adict.htpasswd
  changed_when: true
  tags: configure

- name: Generate SSL certificates
  ansible.builtin.import_tasks: generate_certs.yml
  tags: configure

- name: Restart and enable nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
  tags: install

- name: Ensure firewalld is not masked, enabled and running
  ansible.builtin.systemd:
    name: firewalld
    masked: false
    enabled: true
    state: started
  tags: install

- name: Open port 80/tcp
  ansible.posix.firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
  tags: install

- name: Open port 443/tcp
  ansible.posix.firewalld:
    port: 443/tcp
    permanent: true
    state: enabled
  tags: install

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  changed_when: true
  tags: install
