---
- name: Pandda metering point is installed
  hosts: metering_point
  become: true
  roles:
    - common_tools
    - ipfixprobe_dpdk
    - metering_point

- name: Pandda collector is installed
  hosts: collector
  become: true
  roles:
    - pandda_conf
    - common_tools
    - nemea_collector
    - adict
    - supervisor_restart
