---
- name: IPFIXcol2 package is installed
  ansible.builtin.dnf:
    name:
      - ipfixcol2
    state: present
  tags: install

- name: IPFIXcol2 configuration directory is created
  ansible.builtin.file:
    path: /etc/ipfixcol2
    state: directory
    mode: "0755"
  tags:
    - install
    - configure

  # creates: /etc/ipfixcol2/ipfixcol2-startup.xml
- name: IPFIXcol2 configuration file is created from pandda.yml
  ansible.builtin.command:
    cmd: "{{ pandda_conf_executable }} {{ pandda_conf_opt }}/ipfixcol2_conf.py -f /etc/ipfixcol2/ipfixcol2-startup.xml"
  changed_when: true
  tags:
    - install
    - configure

- name: Supervisord configuration file for IPFIXcol2 is copied
  ansible.builtin.copy:
    src: "supervisor-ipfixcol2.ini"
    dest: /etc/supervisord.d/configs/supervisor-ipfixcol2.ini
    mode: "0755"
  tags:
    - install
    - configure

- name: IPFIXcol2 in supervisor is enabled
  ansible.builtin.command: "supen -n ipfixcol2 -g datasource"
  changed_when: true
  tags:
    - configure

- name: Changes in supervisor are applied
  ansible.builtin.command: "{{ item }}"
  changed_when: true
  loop:
    - "supervisorctl reread"
    - "supervisorctl update"
    - "supervisorctl start datasource:"
  tags:
    - install
    - configure

- name: Firewalld status is checked
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true
  ignore_errors: true
  register: firewalld_status

- name: Firewall port for IPFIXcol2 using firewalld is enabled
  ansible.posix.firewalld:
    port: 4739/tcp
    permanent: true
    immediate: true
    state: enabled
  when: firewalld_status is succeeded and firewalld_status.state == "started"

- name: Firewalld is reloaded
  ansible.builtin.command: firewall-cmd --reload
  changed_when: true
  when: firewalld_status is succeeded and firewalld_status.state == "started"

- name: Firewall port for IPFIXcol2 using iptables is enabled
  ansible.builtin.command: >
    iptables -I INPUT -p tcp --dport 4739 -j ACCEPT
  changed_when: true
  when: firewalld_status is failed or firewalld_status.state != "started"

- name: Iptables configuration is saved
  ansible.builtin.shell: iptables-save > /etc/sysconfig/iptables
  changed_when: true
  when: firewalld_status is failed or firewalld_status.state != "started"
