- name: Install dependencies
  ansible.builtin.dnf:
    name: ["nginx"]
    state: present # noqa package-latest
    update_cache: true

- name: Run dp3 configuration for nginx
  become: true
  ansible.builtin.shell: |
    source {{ venvdir }}/bin/activate && $(which dp3) config nginx --hostname {{ ansible_ssh_host }} --app-name {{ app_name }} --www-root {{ www_root }}
  vars:
    www_root: /var/www/dp3
  args:
    creates:
      - /etc/nginx/nginx.conf
      - /etc/nginx/conf.d/api.conf
      - /var/www/dp3/index.html

- name: Start and enable nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Ensure firewalld is not masked, enabled and running
  ansible.builtin.systemd:
    name: firewalld
    masked: false
    enabled: true
    state: started

- name: Open port 80/tcp
  ansible.posix.firewalld:
    port: 80/tcp
    permanent: true
    state: enabled

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  changed_when: true
