---
- name: ipfixprobe repository is installed
  ansible.builtin.yum_repository:
    name: copr:copr.fedorainfracloud.org:group_CESNET:ipfixprobe
    description: Copr repo for ipfixprobe owned by @CESNET
    baseurl: "{{ url }}/epel-{{ ansible_distribution_major_version }}-$basearch/"
    skip_if_unavailable: true
    gpgcheck: true
    gpgkey: "{{ url }}/pubkey.gpg"
    repo_gpgcheck: false
    enabled: true
  vars:
    url: https://download.copr.fedorainfracloud.org/results/@CESNET/ipfixprobe
